---
name: "📄 Documentation issue"
description: "Found an issue in the documentation? Raise your suggestions here! 😊"
labels: ["📄 aspect: text"]
body:
- type: textarea
id: details
attributes:
  label: Problem
  description: "Briefly describe the problem you found in our documentation"
  placeholder: "(e.g., I noticed that[problem])"
validations:
  required: true
- type: textarea
id: docs_screenshots
attributes:
  label: screenshots
  description: "Please add screenshots if helpful"
validations:
  required: false
- type: textarea
id: description
attributes:
  label: Possible Solution and Benefit
  description: "Describe your solution and how it can help enhance the project"
  placeholder: "(e.g., I suggest[your solution]. This can [add benefit here])"
validations:
  required: true
---
