import Head from "next/head";
import Content from "../components/content";
import Header from "./components/Header";
import Hero from "../components/hero/Hero";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Content />
        <Hero />
      </main>
    </div>
  );
}
